### PR TITLE
Remove the need for sudo at command run

### LINKED ISSUE #2: Need to not have to run it as sudo
@Itai-Nelken You may be able to help me with this, I have been looking into it and I could use something such as

``` 
echo "$data" | sudo tee test.txt

```

How can I silence the echo but still give tee the data it needs

### PR DESCRIPTION
**Pull request by CleanMachine1**
Closes #2 

I forgot about this!

### CODE REVIEW

**Comment by CleanMachine1** [comment]
@Itai-Nelken I have done some testing and I am ready to merge this as soon as you have tested or just given an OK

**Comment by Itai-Nelken** [comment]
You are using dd to clear that file, right?

**Comment by CleanMachine1** [comment]
Yes, I am just writing null to it to empty it

**Comment by Itai-Nelken** [comment]
You could use `echo -n "" > /path/to/file`
More elegant in my opinion.

**Comment by CleanMachine1** [comment]
But then the command needs sudo at start

**Comment by Itai-Nelken** [comment]
oh, so never mind

**Comment by Itai-Nelken** [comment]
actually you are still using sudo for the `dd` command, then why not use the `echo` command with sudo?
I think its more readable and its easier to understand what the script is trying to do.

**Comment by CleanMachine1** [comment]
Because the > isn't affected by sudo

**Comment by CleanMachine1** [comment]
Sudo for the dd because its writing to etc files

**Comment by Itai-Nelken** [comment]
> Because the > isn't affected by sudo

oh, I never realized!

**Pull request merged**
