### PR TITLE
Use clear -x (so previous output scrolls up instead of getting deleted)

### PR DESCRIPTION
**Pull request by Itai-Nelken**
like using ctrl+l

### CODE REVIEW

**Comment by CleanMachine1** [comment]
What is clear x

**Comment by Itai-Nelken** [comment]
when using `clear` it deletes all the previous output.
when using `clear -x` it scrolls down to hide the previous output but doesn't delete it.
I'm not sure that is so clear, so run this to see what I mean:
```bash
for test in {1..40}; do echo "test is $test"; done
```
(this will count to 40)
now run `clear`. you can't scroll up and see the output again.
run the `for` loop again, but this time run `clear -x`. now you can scroll back up and see its output.

**Comment by CleanMachine1** [comment]
Ok, yes that makes more sense to do that!
Just going to add a few more of them then commit it

**Comment by CleanMachine1** [comment]
@Itai-Nelken merged, and done a little more to make it look and feel nicer while using it

**Comment by CleanMachine1** [comment]
PS: this is my first time anyone has PR my repos and i'm really happy that at least someone is helping me :smiley:

**Comment by Itai-Nelken** [comment]
> PS: this is my first time anyone has PR my repos and i'm really happy that at least someone is helping me 😃

you are welcome! :)

**Pull request merged**
